### ISSUE TITLE
Revised World Tags

### ISSUE THREAD

**Issue by mpigsley** [nhr/swn#6]
Is it as simple as updating `swn_data.sql`? Or will there need to be some type of migration file to update the db?

I'd be willing to write out the 40 new tags.

**Comment by xandermathews** [comment]
Speaking as someone who hasn't seriously read the code, there aren't any tables in swn_data.sql that look to be intended for dynamic data, and all I've seen in the db-touching code are selects. That leads me to believe that if you append/replace/whatnot, you can just recreate swn.sqlite.

**Comment by mpigsley** [comment]
Ahh, it's an sqlite db. Nice. I'll try to get those written up.

**Comment by nhr** [comment]
The database tables are all basically just fast lookups. The main Perl module does the random dice rolling and subsequent galactic assembly. So, there are two classes of changes:

1. Totally new stuff that was added in the revised rules
2. Tables where either the dice roll has changed or the contents have changed, or both

Since the changes are most likely to involve both content _and_ dice roll changes, just be aware that any modifications that you make to the .sql file will likely need to be paired with code changes to modify the rolls.

**Comment by mpigsley** [comment]
Closing since you have it covered by https://github.com/nhr/swn/issues/8
